import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Layout from './components/Layout'
import Party from './components/Party'

export default function Home() {
  const [selectedGamer, setSelectedGamer] = useState('0');

  return (
    <div className={styles.container}>
      <Head>
        <title>Raid Loot App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1 items-stretch overflow-hidden min-h-screen">
        <aside className="hidden w-96 overflow-y-auto border-r border-gray-200 bg-white lg:block min-h-screen">
          {/* party member selections */}
          <Party selectedGamer={selectedGamer} onGamerChange={setSelectedGamer} />
        </aside>

        <div className="flex-1 overflow-y-auto">
          <section aria-labelledby="primary-heading" className="flex h-full min-w-0 flex-1 flex-col lg:order-last">
            {/* gear selections for selected party member START */}
            <div className={styles.grid}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>

              <a href="https://nextjs.org/learn" className={styles.card}>
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>

              <a
                href="https://github.com/vercel/next.js/tree/canary/examples"
                className={styles.card}
              >
                <h2>Examples &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </a>

              <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className={styles.card}
              >
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with Vercel.
                </p>
              </a>
            </div>
            {/* gear selections for selected party member END */}
          </section>
        </div>
      </div>
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}