import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Layout from './components/Layout'
import Party from './components/Party'
import GearInterface from './components/GearInterface'

export default function Home() {
  const [selectedGamer, setSelectedGamer] = useState('0');

  return (
    <div className={styles.container}>
      <Head>
        <title>Raid Loot App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1 items-stretch overflow-hidden min-h-screen">
        <aside className="hidden w-96 overflow-y-auto border-r border-gray-200 bg-white lg:block min-h-screen">
          {/* party member selections */}
          <Party selectedGamer={selectedGamer} onGamerChange={setSelectedGamer} />
        </aside>

        <div className="flex-1 overflow-y-auto">
          <section aria-labelledby="primary-heading" className="flex h-full min-w-0 flex-1 flex-col lg:order-last">
            {/* gear selections for selected party member START */}
            <GearInterface gamer={selectedGamer}/>
            {/* gear selections for selected party member END */}
          </section>
        </div>
      </div>
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}