import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Example from './components/Example'
import Layout from './components/Layout'

export default function Test() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Test!
      </h1>
    </div>
  )
}

Test.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}